export { DEFAULT_CONFIG } from "./config/defaults.js";
export { loadConfig } from "./config/loader.js";
export type { Detector, DetectorError, DetectorInput } from "./detectors/base.js";
export { CodeSmellDetector } from "./detectors/code-smell.js";
export { LexicalDetector } from "./detectors/lexical.js";
export { SemanticDetector } from "./detectors/semantic.js";
export { StructuralDetector } from "./detectors/structural.js";
export { formatJson, formatMarkdown, formatReport, formatSarif } from "./engine/reporter.js";
export type { FileInput, ScannerError } from "./engine/scanner.js";
export { Scanner } from "./engine/scanner.js";
export { PatternRegistry } from "./patterns/registry.js";
export { scoreSignals } from "./scoring/scorer.js";
export { scoreToVerdict } from "./scoring/thresholds.js";
export type { SlopGuardianConfig } from "./types/config.js";
export type { DetectorCategory, ScanResult, Severity, Signal, Verdict } from "./types/detection.js";
export type { PatternEntry, PatternFile } from "./types/pattern.js";
export type { FormatOptions, ReportFormat } from "./types/report.js";
